server:
  port: 8081
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    request:
      exchange:
        producer: ex.producer.app
      routing-key:
        producer: rk.producer.app
      deadletter:
        producer: dl.producer.app